labels:
  inProgress: "s: in progress"
  awaitingReview: "s: awaiting review"
prs:
  drafts:
    markInProgress: true
    markAwaitingReview: true
  reviews:
    required: 2
    maintainers:
      required: 1
