labels:
  inProgress: "s: in progress"
  awaitingReview: "s: awaiting review"
  awaitingMerge: "s: awaiting merge"
prs:
  drafts:
    markInProgress: true
    markAwaitingReview: true
  reviews:
    required: 2
