on:
  issues:
    types: [opened, closed, labeled, unlabeled, milestoned, demilestoned]
  pull_request:
    types: [labeled, unlabeled, opened, closed, converted_to_draft, ready_for_review]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  pain:
    name: Pain
    runs-on: ubuntu-latest
    steps:
      - uses: ooliver1/triagecat@master
        with:
          TOKEN: ${{ secrets.PAT }}
